USE MASTER
IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME = 'EcoSiteDB')
DROP DATABASE EcoSiteDB
GO

CREATE DATABASE EcoSiteDB
GO

USE EcoSiteDB
GO

--IF EXISTS (SELECT * FROM SYSOBJECTS
--	WHERE ID = OBJECT_ID('dbo.*T*') AND SYSSTAT & 0XF = 3)
--	DROP TABLE dbo.*
--GO

--CREATE TABLE dbo.*T*
--(
-- CONSTRAINT PK_*T* PRIMARY KEY NONCLUSTERED (*PK*),
--)